<a href="https://colab.research.google.com/github/RohanAwate9020/Python-practice-program/blob/main/Activity1Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
import numpy as np
#numpy library 

arr=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[12,4,5,6]]])
#Definig and initializing array

print("Elements of Array are:")
print(arr)
#printing array

print("\n********************************************************************")
print("Performing multiple operations on array:")


print("\n1.\tType of array:", type(arr))
#printing type of array


print("2.\tThe array is:", arr.ndim,"dimensional")
#printing dimensions of array

print("3.\tThe Size of array(Printing the elements stored in array):",arr.size)
#printing the size of array

print("4.\tArray Store element of type:",arr.dtype)
#printing array element datatype





Elements of Array are:
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [12  4  5  6]]]

********************************************************************
Performing multiple operations on array:

1.	Type of array: <class 'numpy.ndarray'>
2.	The array is: 3 dimensional
3.	The Size of array(Printing the elements stored in array): 16
4.	Array Store element of type: int64


In [ ]:
print("Hii")

Hii
