<a href="https://colab.research.google.com/github/RohanAwate9020/Python-practice-program/blob/main/Activity1Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
import numpy as np
#numpy library 

arr=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[12,4,5,6]]])
#Definig and initializing array

print("Elements of Array are:")
print(arr)
#printing array

print("\n********************************************************************")
print("Performing multiple operations on array:")


print("\n1.\tType of array:", type(arr))
#printing type of array


print("2.\tThe array is:", arr.ndim,"dimensional")
#printing dimensions of array

print("3.\tThe Size of array(Printing the elements stored in array):",arr.size)
#printing the size of array

print("4.\tArray Store element of type:",arr.dtype)
#printing array element datatype





Elements of Array are:
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [12  4  5  6]]]

********************************************************************
Performing multiple operations on array:

1.	Type of array: <class 'numpy.ndarray'>
2.	The array is: 3 dimensional
3.	The Size of array(Printing the elements stored in array): 16
4.	Array Store element of type: int64


In [53]:
import numpy as np
a = np.array([1,2,5,3,6,7,8,9])
print("Elements of Array are:")
print(a)
print("\nPerforming Operations on Array")
print('\n************************************************************************')

print ("1.\tAdding 1 to every element:", a+1)
# adding 1 to every element
  
print ("2.\tSubtracting 3 from each element:", a-3)
# subtract 3 from each element
  
# multiply each element by 10
print ("3.\tMultiplying each element by 10:", a*10)
  
# square each element
print ("4.\tSquaring each element:", a**2)
  
# modify existing array
a *= 2
print ("5.\tDoubled each element of original array:", a)

  

Elements of Array are:
[1 2 5 3 6 7 8 9]

Performing Operations on Array

************************************************************************
1.	Adding 1 to every element: [ 2  3  6  4  7  8  9 10]
2.	Subtracting 3 from each element: [-2 -1  2  0  3  4  5  6]
3.	Multiplying each element by 10: [10 20 50 30 60 70 80 90]
4.	Squaring each element: [ 1  4 25  9 36 49 64 81]
5.	Doubled each element of original array: [ 2  4 10  6 12 14 16 18]


In [34]:
import numpy as np


arr = np.array([(8,9,10),(11,12,13)])
#Definig and initializing array

print("Array before Reshape")
print(arr)
#printing array before reshape

arr=arr.reshape(3,2)
#function to Reshape array 

print("\nArray After applying reshape function on it:")
print(arr)

Array before Reshape
[[ 8  9 10]
 [11 12 13]]

Array After applying reshape function on it:
[[ 8  9]
 [10 11]
 [12 13]]


In [47]:
import numpy as np

print("Elements of array are:")
a=np.array([(1,2,3,4),(3,4,5,6)])
print(a)

print("\nPerforming slicing operations on Array:")
print("\n****************************************************************")
print("\n1.\tPrinting third elemnt of first index:",a[0,2])
print("2.\tPrinting Thired element of first and second index:",a[0:,2])
print("3.\tPrinting Smallest element from Array:",a.min())
print("4.\tPrinting Largest element form Array:",a.max())
print("5.\tPrinting the sum of all element of Array:",a.sum())

Elements of array are:
[[1 2 3 4]
 [3 4 5 6]]

Performing slicing operations on Array:

****************************************************************

1.	Printing third elemnt of first index: 3
2.	Printing Thired element of first and second index: [3 5]
3.	Printing Smallest element from Array: 1
4.	Printing Largest element form Array: 6
5.	Printing the sum of all element of Array: 28


In [56]:
import numpy as np


x= np.array([(1,2,3),(3,4,5)])
print("Elements of first array:")
print(x)


y= np.array([(1,2,3),(3,4,5)])
print("\nElements of Second array:")
print(y)

print("\nAddition of the element of both Array")
print(x+y)

Elements of first array:
[[1 2 3]
 [3 4 5]]

Elements of Second array:
[[1 2 3]
 [3 4 5]]

Addition of the element of both Array
[[ 2  4  6]
 [ 6  8 10]]


In [66]:
import numpy as np 
print("Elements of array are:")
a = np.array([1,2,3,4,5,6])
print(a)

print("\nPerforming operations on Array:")
print("\n****************************************************************")   

print ('Adding the elements to array:')
print(np.append(a, [7,8,9]) )
#Adding the new elements at the end of array
 

Elements of array are:
[1 2 3 4 5 6]

Performing operations on Array:

****************************************************************
Adding the elements to array:
[1 2 3 4 5 6 7 8 9]
